### ISSUE TITLE
Missing pre-trained network on MiniImagenet

### ISSUE THREAD

**Issue by DanielShalam** [xiangyu8/PT-MAP-sf#4]
Hello, 
Thank you for the pre-trained network you supplied.
I'm trying to reproduce your results, but the checkpoints files miss the .tar file of 'both' for MiniImagenet.

Can you supply this checkpoint file?

**Comment by xiangyu8** [comment]
Thanks for your interest. I trained both branches separately. Then I integrated them in save_feature_both file to save the integrated features and test.

**Comment by DanielShalam** [comment]
Thank you for your response.

I understand the way to extract those features. Still, I'm facing issues downloading some of the packages you use to extract those features in save_plk_both.

May you supply the plk file for MiniImagenet 'both' as you supplied for cifar and CUB?

**Comment by xiangyu8** [comment]
I have updated the checkpoints link. You should be able to download it now.

**Comment by DanielShalam** [comment]
Thank you.
